default_hosts = [
  {name: 'GitHub', url: 'https://github.com', kind: 'github'},
  {name: 'GitLab.com', url: 'https://gitlab.com', kind: 'gitlab'},
  {name: 'Bitbucket.org', url: 'https://bitbucket.org', kind: 'bitbucket'},
  {name: 'SourceHut', url: 'https://sr.ht', kind: 'sourcehut'},
  {name: 'Gitea.com', url: 'https://gitea.com', kind: 'gitea'},
  {name: "Codeberg.org", url: "https://codeberg.org", kind: "gitea", org: 'Codeberg-org'},
  {name: "git.fsfe.org", url: "https://git.fsfe.org", kind: "gitea", org: 'fsfe'},
  {name: "opendev.org", url: "https://opendev.org", kind: "gitea", org: 'openstack-infra'},
  {name: "code-repo.d4science.org", url: "https://code-repo.d4science.org", kind: "gitea", org: 'd4science'},
  {name: "salsa.debian.org", url: "https://salsa.debian.org", kind: "gitlab", org: 'debian'},
  {name: "gitlab.haskell.org", url: "https://gitlab.haskell.org", kind: "gitlab", org: 'haskell'},
  {name: "framagit.org", url: "https://framagit.org", kind: "gitlab", org: 'framasoft'},
  {name: "gitlab.gentoo.org", url: "https://gitlab.gentoo.org", kind: "gitlab", org: 'gentoo'},
  {name: "gitlab.freedesktop.org", url: "https://gitlab.freedesktop.org", kind: "gitlab", org: 'freedesktop'},
  {name: "gitlab.arm.com", url: "https://gitlab.arm.com", kind: "gitlab", org: 'ARM-software'},
  {name: "invent.kde.org", url: "https://invent.kde.org", kind: "gitlab", org: 'kde'},
  {name: "gitlab.xfce.org", url: "https://gitlab.xfce.org", kind: "gitlab", org: 'xfce-mirror'},
  {name: "gitlab.alpinelinux.org", url: "https://gitlab.alpinelinux.org", kind: "gitlab", org: 'alpinelinux'},
  {name: "git.pleroma.social", url: "https://git.pleroma.social", kind: "gitlab", org: 'pleroma-social'},
  {name: "git.gusted.xyz", url: "https://git.gusted.xyz/", kind: "forgejo"},
  {name: "git.tubul.net", url: "https://git.tubul.net", kind: "forgejo"},
  {name: "git.batsense.net", url: "https://git.batsense.net", kind: "forgejo"},
  {name: "code.forgejo.org", url: "https://code.forgejo.org", kind: "forgejo"},
  {name: "git.feldspaten.org", url: "https://git.feldspaten.org", kind: "forgejo"},
  {name: "git.berlin.ccc.de", url: "https://git.berlin.ccc.de", kind: "forgejo"},
  {name: "git.freetards.xyz", url: "https://git.freetards.xyz", kind: "forgejo"},
  {name: "git.tecosaur.net", url: "https://git.tecosaur.net", kind: "forgejo"},
  {name: "source.mcwhirter.io", url: "https://source.mcwhirter.io", kind: "forgejo"},
  {name: "git.leafee98.com", url: "https://git.leafee98.com", kind: "forgejo"},
  {name: "git.systemausfall.org", url: "https://git.systemausfall.org", kind: "forgejo"},
  {name: "git.mastodont.cat", url: "https://git.mastodont.cat", kind: "forgejo"},
  {name: "forgejo.sny.sh", url: "https://forgejo.sny.sh", kind: "forgejo"},
  {name: "git.joinplu.me", url: "https://git.joinplu.me", kind: "forgejo"},
  {name: "git.gmem.ca", url: "https://git.gmem.ca", kind: "forgejo"},
  {name: "gitea.jotoho.de", url: "https://gitea.jotoho.de", kind: "forgejo"},
  {name: "git.trwnh.com", url: "https://git.trwnh.com", kind: "forgejo"},
  {name: "git.woodbine.nyc", url: "https://git.woodbine.nyc", kind: "forgejo"},
  {name: "git.kabelsalat.ch", url: "https://git.kabelsalat.ch", kind: "forgejo"},
  {name: "git.friendi.ca", url: "https://git.friendi.ca", kind: "forgejo"},
  {name: "git.chinwag.org", url: "https://git.chinwag.org", kind: "forgejo"},
  {name: "git.proyectozero.org", url: "https://git.proyectozero.org", kind: "forgejo"},
  {name: "git.nold.in", url: "https://git.nold.in", kind: "forgejo"},
  {name: "repo.prod.meissa.de", url: "https://repo.prod.meissa.de", kind: "forgejo"},
  {name: "eugit.opencloud.lu", url: "https://eugit.opencloud.lu", kind: "forgejo"},
  {name: "forgejo.praxis.red", url: "https://forgejo.praxis.red", kind: "forgejo"},
  {name: "git.lain.faith", url: "https://git.lain.faith", kind: "gitea"},
  {name: "git.vnecke.de", url: "https://git.vnecke.de", kind: "forgejo"},
  {name: "git.sublimity.de", url: "https://git.sublimity.de", kind: "forgejo"},
  {name: "git.chandlerswift.com", url: "https://git.chandlerswift.com", kind: "forgejo"},
  {name: "git.data.coop", url: "https://git.data.coop", kind: "forgejo"},
  {name: "git.rico-schmidt.name", url: "https://git.rico-schmidt.name", kind: "forgejo"},
  {name: "code.ewintr.nl", url: "https://code.ewintr.nl", kind: "forgejo"},
  {name: "git.penguincoder.org", url: "https://git.penguincoder.org", kind: "forgejo"},
  {name: "tacksupport.net/git", url: "https://tacksupport.net/git", kind: "forgejo"},
  {name: "gitea.zionetrix.net", url: "https://gitea.zionetrix.net", kind: "forgejo"},
  {name: "git.mattcen.com", url: "https://git.mattcen.com", kind: "forgejo"},
  {name: "code.gabe.rocks", url: "https://code.gabe.rocks", kind: "forgejo"},
  {name: "git.arachnitech.com", url: "https://git.arachnitech.com", kind: "forgejo"},
  {name: "git.tarasis.net", url: "https://git.tarasis.net", kind: "forgejo"},
  {name: "git.rossabaker.com", url: "https://git.rossabaker.com", kind: "forgejo"},
  {name: "git.nixre.net", url: "https://git.nixre.net", kind: "forgejo"},
  {name: "git.keleti.dev", url: "https://git.keleti.dev", kind: "forgejo"},
  {name: "git.distrust.co", url: "https://git.distrust.co", kind: "forgejo"},
  {name: "code.ryuslash.org", url: "https://code.ryuslash.org", kind: "forgejo"},
  {name: "www.zyria.de/git", url: "https://www.zyria.de/git", kind: "forgejo"},
  {name: "git.tagisow.dev", url: "https://git.tagisow.dev", kind: "forgejo"},
  {name: "forgejo.pschneider.fr", url: "https://forgejo.pschneider.fr", kind: "forgejo"},
  {name: "gitea.voidc.de", url: "https://gitea.voidc.de", kind: "forgejo"},
  {name: "git.pavluk.org", url: "https://git.pavluk.org", kind: "forgejo"},
  {name: "git.php.fail", url: "https://git.php.fail", kind: "forgejo"},
  {name: "git.blobfox.coffee", url: "https://git.blobfox.coffee", kind: "forgejo"},
  {name: "gitea.voidc.de", url: "https://gitea.voidc.de", kind: "forgejo"},
  {name: "git.pavluk.org", url: "https://git.pavluk.org", kind: "forgejo"},
  {name: "git.kun.is", url: "https://git.kun.is", kind: "forgejo"},
  {name: "git.roberttimis.com", url: "https://git.roberttimis.com", kind: "forgejo"},
  {name: "git.bloat.cat", url: "https://git.bloat.cat", kind: "forgejo"},
  {name: "forge.babariviere.com", url: "https://forge.babariviere.com", kind: "forgejo"},
  {name: "git.rewritesarebliss.com", url: "https://git.rewritesarebliss.com", kind: "forgejo"},
  {name: "git.spec.cat", url: "https://git.spec.cat", kind: "forgejo"},
  {name: "git.lonelyformula.com", url: "https://git.lonelyformula.com", kind: "forgejo"},
  {name: 'gitea.kerbores.com', url: 'https://gitea.kerbores.com', kind: 'gitea'},
  {name: 'gitea.i15.nl', url: 'https://gitea.i15.nl', kind: 'gitea'},
  {name: 'gitea.cavar.net', url: 'https://gitea.cavar.net', kind: 'gitea'},
  {name: 'gitea.vbgn.be', url: 'https://gitea.vbgn.be', kind: 'gitea'},
  {name: 'gitea.kosmos.org', url: 'https://gitea.kosmos.org', kind: 'gitea'},
  {name: 'gitea.com', url: 'https://gitea.com', kind: 'gitea'},
  {name: 'gitea.kiwe-technik.de', url: 'https://gitea.kiwe-technik.de', kind: 'gitea'},
  {name: 'gitea.nulo.in', url: 'https://gitea.nulo.in', kind: 'gitea'},
  {name: 'gitea.unknown.name', url: 'https://gitea.unknown.name', kind: 'gitea'},
  {name: 'gitea.raphaelpiccolo.com', url: 'https://gitea.raphaelpiccolo.com', kind: 'gitea'},
  {name: 'gitea.teamortix.com', url: 'https://gitea.teamortix.com', kind: 'gitea'},
  {name: 'gitea.nitowa.xyz', url: 'https://gitea.nitowa.xyz', kind: 'gitea'},
  {name: 'gitea.dyne.org', url: 'https://gitea.dyne.org', kind: 'gitea'},
  {name: 'gitea.deepak.science', url: 'https://gitea.deepak.science', kind: 'gitea'},
  {name: 'gitea.tforgione.fr', url: 'https://gitea.tforgione.fr', kind: 'gitea'},
  {name: 'gitea.statsd.de', url: 'https://gitea.statsd.de', kind: 'gitea'},
  {name: 'gitea.code-infection.com', url: 'https://gitea.code-infection.com', kind: 'gitea'},
  {name: 'gitea.mahillmann.de', url: 'https://gitea.mahillmann.de', kind: 'gitea'},
  {name: 'gitea.olznet.de', url: 'https://gitea.olznet.de', kind: 'gitea'},
  {name: 'gitea.dwayne.xyz', url: 'https://gitea.dwayne.xyz', kind: 'gitea'},
  {name: 'gitea.sebastian-tobie.de', url: 'https://gitea.sebastian-tobie.de', kind: 'gitea'},
  {name: 'gitea.tfnux.org', url: 'https://gitea.tfnux.org', kind: 'gitea'},
  {name: 'gitea.suyono.dev', url: 'https://gitea.suyono.dev', kind: 'gitea'},
  {name: 'gitea.drecks-provider.de', url: 'https://gitea.drecks-provider.de', kind: 'gitea'},
  {name: 'gitea.difrex.ru', url: 'https://gitea.difrex.ru', kind: 'gitea'},
  {name: 'gitea.schlittermann.de', url: 'https://gitea.schlittermann.de', kind: 'gitea'},
  {name: 'gitea.arpa.li', url: 'https://gitea.arpa.li', kind: 'gitea'},
  {name: 'gitea.nehmer.net', url: 'https://gitea.nehmer.net', kind: 'gitea'},
  {name: 'gitea.elkins.co', url: 'https://gitea.elkins.co', kind: 'gitea'},
  {name: 'gitea.linuxcode.net', url: 'https://gitea.linuxcode.net', kind: 'gitea'},
  {name: 'gitea.digitalcircle.com.br', url: 'https://gitea.digitalcircle.com.br', kind: 'gitea'},
  {name: 'gitea.ma5k.online', url: 'https://gitea.ma5k.online', kind: 'gitea'},
  {name: 'git.envs.net', url: 'https://git.envs.net', kind: 'gitea'},
  {name: 'git.mills.io', url: 'https://git.mills.io', kind: 'gitea'},
  {name: 'forgejo.sny.sh', url: 'https://forgejo.sny.sh', kind: 'forgejo'},
  {name: 'forgejo.vanten-s.com', url: 'https://forgejo.vanten-s.com', kind: 'forgejo'},

  {name: 'git.digisthesia.com', url: 'https://git.digisthesia.com', kind: 'gitea'},
  {name: 'git.panekj.dev', url: 'https://git.panekj.dev', kind: 'gitea'},
  {name: 'dev.cvsck.ru', url: 'https://dev.cvsck.ru', kind: 'gitea'},
  {name: 'git.netflux.io', url: 'https://git.netflux.io', kind: 'gitea'},
  {name: 'code.lag.net', url: 'https://code.lag.net', kind: 'gitea'},
]

default_hosts.each do |host|
  h = Host.find_or_initialize_by(url: host[:url])
  h.assign_attributes(host)
  h.save
end